version: "3"
services:
  admin-be:
    build:
      context: ../server
      dockerfile: Dockerfile.dev
      args:
        NODE_ENV: development
    volumes:
      - ../server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
      - redis

  admin-fe:
    build:
      context: ../client
      dockerfile: Dockerfile.dev
      args:
        NODE_ENV: development
    volumes:
      - ../client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  postgres:
    image: postgres:14.8
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres-local-password-8888"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "1000:80"
    volumes:
      - ./nginx/dev/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  postgres-data:
  redis-data: